### ISSUE TITLE
UnicodeDecodeError will be raised when unparsing chinese characters encoded by utf-8

### ISSUE THREAD

**Issue by dlf412** [martinblech/xmltodict#108]
Python 2.7.3 (default, Aug  1 2012, 05:16:07) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmltodict
>>> print xmltodict.__version__
0.9.2
>>> test = {"root":{"data":[{"case1": "hello world"}, {"case2": "你好，世界"}]}}
>>> test1 = {"root":{"data":{"case1": "hello world"}}}
>>> test2 = {"root":{"data":{"case2": "你好，世界"}}}
>>> xmltodict.unparse(test1)
u'<?xml version="1.0" encoding="utf-8"?>\n<root><data><case1>hello world</case1></data></root>'
>>> xmltodict.unparse(test2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 333, in unparse
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 296, in _emit
    pretty, newl, indent)
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 296, in _emit
    pretty, newl, indent)
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 274, in _emit
    v = _unicode(v)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
>>> xmltodict.unparse(test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 333, in unparse
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 296, in _emit
    pretty, newl, indent)
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 296, in _emit
    pretty, newl, indent)
  File "/usr/local/lib/python2.7/dist-packages/xmltodict.py", line 274, in _emit
    v = _unicode(v)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
>>> "你好，世界"
'\xe4\xbd\xa0\xe5\xa5\xbd\xef\xbc\x8c\xe4\xb8\x96\xe7\x95\x8c'

**Comment by KenetJervet** [comment]
@dlf412 xmltodict can't guess the encoding of your strings so it will simply follow the default encoding (in Python is ascii). You'll have to use unicode values instead: ```u"你好，世界"```

**Comment by KenetJervet** [comment]
But I do wonder if it is reasonable to decode the string as per the ```encoding``` argument (default to 'utf-8'). Although currently it is intended to only influence the prolog and unicode characters.

**Comment by martinblech** [comment]
@KenetJervet is right, `xmltodict` expects unicode strings and won't try to decode binary UTF-8 encoded data.
