### ISSUE TITLE
xml.parsers.expat.ExpatError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by mikusjelly** [martinblech/xmltodict#154]
```xml 
        <service
            android:name="o.ﺮ"
            BAD_STRING="true">
        </service>
        <service
            android:name="o.ĵ"
            BAD_STRING="true">
        </service>
        <service
            android:name="o.ๆ"
            BAD_STRING="true">
        </service>
```

```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\xmltodict.py", line 309, in parse
    parser.ParseFile(xml_input)
TypeError: argument must have 'read' attribute

During handling of the above exception, another exception occurred:
...
  File "C:\Anaconda3\lib\site-packages\xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 260, column 0
```

**Comment by martinblech** [comment]
Looks like this was covered by #150, please reopen if you still have this issue with v0.11.0.

**Comment by mikusjelly** [comment]
Thank you. It works.
