### ISSUE TITLE
Cannot parse &

### ISSUE THREAD

**Issue by barroca** [martinblech/xmltodict#18]
Cannot parse xml with & character:

```
import xmltodict
xmltodict.parse("<xtra> Cal\&Atilde;&sect;a Jeans Alex com Lavagem Clara - Colcci</xtra>")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/barroca/Developer/heroku/meliuz/meliuz-env/lib/python2.7/site-packages/xmltodict.py", line 189, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: undefined entity: line 1, column 11
```

It might be a problem with expat.

**Comment by eric-wieser** [comment]
I assume you mean `&amp;` which github helpfully replaced back to `&` for you.

**Comment by barroca** [comment]
indeed.
