### ISSUE TITLE
XML or text declaration not at start of entity

### ISSUE THREAD

**Issue by Doskulov** [martinblech/xmltodict#187]
how to parse with xml main tag, if i will remove it everything works fine, but i'm integrating with other service, so i need to parse with this:
data = """
<?xml version='1.0' encoding='Windows-1251' standalone='yes'?>
.....
"""

**Comment by javadev** [comment]
```xml
<?xml version="1.0" encoding="Windows-1251" standalone="yes"?>
<a></a>
```
may be converted to
```json
{
  "a": {
  },
  "#encoding": "Windows-1251",
  "#standalone": "yes"
}
```

**Comment by AlexHilson** [comment]
Looks like the exception text is referring to the new line at the start of the xml. 

Fails:
```python
r = xmltodict.parse('''
... <?xml version="1.0" encoding="Windows-1251" standalone="yes"?>
... <a></a>
... ''')
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/ubuntu/environment/mdda-service/artefacts/record-ingestion/venv/lib/python3.7/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: XML or text declaration not at start of entity: line 2, column 0
```

Works (no whitespace):

```python
r = xmltodict.parse(
... '''<?xml version="1.0" encoding="Windows-1251" standalone="yes"?>
... <a></a>
... ''')
>>> r
OrderedDict([('a', None)])
```

Works (no xml declaration):

```python
r = xmltodict.parse('''
... <a></a>
... ''')
>>> r
OrderedDict([('a', None)])
```

**Comment by sashank27** [comment]
@AlexHilson is it possible to parse an XML having a newline at the beginning?
I am getting the XML response from a server, and there is nothing I can do to remove that line from the server-side. I can do some file manipulation at the client-side, but I expect the library to perform that task.

I can even contribute in developing if this can be an added feature
