### ISSUE TITLE
[BUG] XML UTF-8 with BOM fails

### ISSUE THREAD

**Issue by Kochise** [martinblech/xmltodict#330]
You can test any XML file with a BOM :

```batch
D:\Pyenv310>xml22yaml -i "d:\Pyenv310\TEST\Alarms.xml" -o "d:\Pyenv310\TEST\Alarms.yaml"
Traceback (most recent call last):
  File "D:\Pyenv310\Python\Lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Pyenv310\Python\Lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Pyenv310\Python\Scripts\xml22yaml.exe\__main__.py", line 7, in <module>
  File "D:\Pyenv310\Python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\Pyenv310\Python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\Pyenv310\Python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Pyenv310\Python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\Pyenv310\Python\lib\site-packages\yaplon\__main__.py", line 701, in xml2yaml
    reader.xml(
  File "D:\Pyenv310\Python\lib\site-packages\yaplon\reader.py", line 71, in xml
    obj = oxml.parse(input.read(), process_namespaces=namespaces)
  File "D:\Pyenv310\Python\lib\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 1
```

Regards.

**Comment by mpf82** [comment]
You can specify the encoding in parse(), the default is utf-8

IANA currently lists [250+ character encodings](https://www.iana.org/assignments/character-sets/character-sets.xhtml).

Python natively supports a subset of [109 encodings](https://docs.python.org/3/library/codecs.html#standard-encodings) (plus some Python specific encodings).

You cannot possibly expect xmltodict to know or to guess which one your input uses.

**Comment by Kochise** [comment]
```batch
set "PYTHONIOENCODING=utf8"
```

`xmltodict ` shouldn't care about BOM

[Alarms.xml.txt](https://github.com/martinblech/xmltodict/files/11801390/Alarms.xml.txt)

**Comment by Kochise** [comment]
Just using https://github.com/twardoch/yaplon
