### ISSUE TITLE
AttributeError: 'int' object has no attribute 'replace'

### ISSUE THREAD

**Issue by centralniak** [martinblech/xmltodict#86]
Hi,

If we try to `xmldict.unparse` the following dict it will fail:

```
{'MessageData': {
    '@infotype': 0,
    '#text': '08',
}}
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/tmp/xmltodictest/lib/python2.7/site-packages/xmltodict.py", line 333, in unparse
    **kwargs)
  File "/tmp/xmltodictest/lib/python2.7/site-packages/xmltodict.py", line 296, in _emit
    pretty, newl, indent)
  File "/tmp/xmltodictest/lib/python2.7/site-packages/xmltodict.py", line 290, in _emit
    content_handler.startElement(key, AttributesImpl(attrs))
  File "/usr/lib64/python2.7/xml/sax/saxutils.py", line 159, in startElement
    self._write(u' %s=%s' % (name, quoteattr(value)))
  File "/usr/lib64/python2.7/xml/sax/saxutils.py", line 66, in quoteattr
    data = escape(data, entities)
  File "/usr/lib64/python2.7/xml/sax/saxutils.py", line 32, in escape
    data = data.replace("&", "&amp;")
AttributeError: 'int' object has no attribute 'replace'
```

It's important that infotype is an attribute. It will work fine if an integer is a text node. 

**0.9.2**

**Comment by centralniak** [comment]
Although this is easy to fix by casting to `_unicode` it would require changing the assertions in tests to something less precise than `assertEqual`. 

@martinblech Let me know if you want this fixed, I'm happy work on this if so.

**Comment by martinblech** [comment]
@centralniak Thank you for reporting this. Sounds like a nice improvement to `xmltodict`, I would love to review and merge a pull request for this.

**Comment by muffl0n** [comment]
The STIXProject had the same problem: https://github.com/STIXProject/python-stix/issues/220
They fixed it by using unicode() around all values: https://github.com/STIXProject/python-stix/pull/233/files#diff-a79d7dfc915093fc3e522827c21b2211R290
